// From Zeff UI - shouldn't rely on this entirely
/* exported abilityList */
var abilityList = [
    // ROLE ACTIONS
    // Tank
    {
        id: 7531,
        name: "Rampart",
        name_cn: "铁壁",
        name_de: "Schutzwall",
        name_en: "Rampart",
        name_fr: "Rempart",
        name_jp: "ランパート",
        name_kr: "철벽 방어",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "Tank",
        level: 8,
        duration: 20,
        cooldown: 90,
        type: "Mitigation",
        icon: "https://xivapi.com/i/000000/000801.png",
        color: "--filter-light-blue",
        order: 0,
    },
    {
        id: 7548,
        name: "Arm's Length",
        name_cn: "亲疏自行",
        name_de: "Abtausch",
        name_en: "Arm's Length",
        name_fr: "Portée de bras",
        name_jp: "アームズレングス",
        name_kr: "거리 유지",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "Tank",
        level: 32,
        duration: 6,
        cooldown: 120,
        type: "Mitigation",
        icon: "https://xivapi.com/i/000000/000822.png",
        color: "--filter-light-blue",
        order: 1,
    },
    {
        id: 7535,
        name: "Reprisal",
        name_cn: "雪仇",
        name_de: "Reflexion",
        name_en: "Reprisal",
        name_fr: "Rétorsion",
        name_jp: "リプライザル",
        name_kr: "앙갚음",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "Tank",
        level: 22,
        duration: 10,
        cooldown: 60,
        type: "Mitigation",
        icon: "https://xivapi.com/i/000000/000806.png",
        color: "--filter-light-blue",
        order: 2,
    },
    {
        id: 7535,
        name: "Reprisal",
        name_cn: "雪仇",
        name_de: "Reflexion",
        name_en: "Reprisal",
        name_fr: "Rétorsion",
        name_jp: "リプライザル",
        name_kr: "앙갚음",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "Tank",
        level: 22,
        duration: 10,
        cooldown: 60,
        type: "Party",
        icon: "https://xivapi.com/i/000000/000806.png",
        color: "--filter-light-blue",
        order: 2,
    },
    // Caster
    {
        id: 7561,
        name: "Swiftcast",
        name_cn: "即刻咏唱",
        name_de: "Spontaneität",
        name_en: "Swiftcast",
        name_fr: "Magie prompte",
        name_jp: "迅速魔",
        name_kr: "신속한 마법",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "Caster",
        level: 18,
        duration: 10,
        cooldown: 60,
        type: "Party",
        icon: "https://xivapi.com/i/000000/000866.png",
        color: "--filter-light-blue",
        order: 0,
    },
    {
        id: 7560,
        name: "Addle",
        name_cn: "昏乱",
        name_de: "Stumpfsinn",
        name_en: "Addle",
        name_fr: "Embrouillement",
        name_jp: "アドル",
        name_kr: "정신 교란",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "CasterDPS",
        level: 8,
        duration: 10,
        cooldown: 90,
        type: "Party",
        icon: "https://xivapi.com/i/000000/000861.png",
        color: "--filter-light-blue",
        order: 1,
    },
    // Melee DPS
    {
        id: 7549,
        name: "Feint",
        name_cn: "牵制",
        name_de: "Zermürben",
        name_en: "Feint",
        name_fr: "Restreinte",
        name_jp: "牽制",
        name_kr: "견제",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "MeleeDPS",
        level: 22,
        duration: 10,
        cooldown: 90,
        type: "Party",
        icon: "https://xivapi.com/i/000000/000828.png",
        color: "--filter-light-blue",
        order: 0,
    },
    // AST
    // DoTs
    {
        id: 838,
        name: "Combust",
        name_cn: "烧灼",
        name_de: "Konjunktion",
        name_en: "Combust",
        name_fr: "Conjonction supérieure",
        name_jp: "コンバス",
        name_kr: "컴버스",
        enabled: true,
        tts: true,
        ttstype: 1,
        job: "AST",
        type: "DoT",
        icon: "https://xivapi.com/i/013000/013213.png",
        color: "--filter-light-blue",
        order: 0,
    },
    {
        id: 843,
        name: "Combust II",
        name_cn: "炽灼",
        name_de: "Konjunktion II",
        name_en: "Combust II",
        name_fr: "Conjonction supérieure II",
        name_jp: "コンバラ",
        name_kr: "컴버라",
        enabled: true,
        tts: true,
        ttstype: 1,
        job: "AST",
        type: "DoT",
        icon: "https://xivapi.com/i/013000/013214.png",
        color: "--filter-light-blue",
        order: 0,
    },
    {
        id: 1881,
        name: "Combust III",
        name_cn: "焚灼",
        name_de: "Konjunktion III",
        name_en: "Combust III",
        name_fr: "Conjonction supérieure III",
        name_jp: "コンバガ",
        name_kr: "컴버가",
        enabled: true,
        tts: true,
        ttstype: 1,
        job: "AST",
        type: "DoT",
        icon: "https://xivapi.com/i/013000/013248.png",
        color: "--filter-light-blue",
        order: 0,
    },
    // Self-Buffs
    {
        id: 1878,
        name: "Divination",
        name_cn: "占卜",
        name_de: "Weissagung",
        name_en: "Divination",
        name_fr: "Divination",
        name_jp: "ディヴィネーション",
        name_kr: "점복",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "AST",
        type: "Buff",
        icon: "https://xivapi.com/i/013000/013245.png",
        color: "--filter-light-gold",
        order: 0,
    },
    {
        id: 841,
        name: "Lightspeed",
        name_cn: "光速",
        name_de: "Lichtgeschwindigkeit",
        name_en: "Lightspeed",
        name_fr: "Vitesse de la lumière",
        name_jp: "ライトスピード",
        name_kr: "광속 시전",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "AST",
        type: "Buff",
        icon: "https://xivapi.com/i/013000/013220.png",
        color: "--filter-light-gold",
        order: 1,
    },
    {
        id: 16559,
        name: "Neutral Sect",
        name_cn: "中间学派",
        name_de: "Neutral",
        name_en: "Neutral Sect",
        name_fr: "Adepte de la neutralité",
        name_jp: "ニュートラルセクト",
        name_kr: "하루별읽기",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "AST",
        type: "Buff",
        icon: "https://xivapi.com/i/013000/013253.png",
        color: "--filter-light-pink",
        order: 2,
    },
    {
        id: 3612,
        name: "Synastry",
        name_cn: "星位合图",
        name_de: "Synastrie",
        name_en: "Synastry",
        name_fr: "Synastrie",
        name_jp: "シナストリー",
        name_kr: "궁합",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "AST",
        type: "Buff",
        icon: "https://xivapi.com/i/013000/013223.png",
        color: "--filter-light-blue",
        order: 3,
    },
    // Raid Buffs
    {
        id: 16552,
        name: "Divination",
        name_cn: "占卜",
        name_de: "Weissagung",
        name_en: "Divination",
        name_fr: "Divination",
        name_jp: "ディヴィネーション",
        name_kr: "점복",
        enabled: true,
        tts: true,
        ttstype: 2,
        job: "AST",
        level: 50,
        duration: 15,
        cooldown: 120,
        type: "RaidBuff",
        icon: "https://xivapi.com/i/003000/003553.png",
        color: "--filter-light-gold",
        order: 0,
    },
    // AST Cards
    {
        id: 17055,
        name: "Play",
        name_cn: "出卡",
        name_de: "Ausspielen",
        name_en: "Play",
        name_fr: "Dévoilement",
        name_jp: "プレイ",
        name_kr: "카드 풀이",
        enabled: true,
        tts: true,
        ttstype: 2,
        job: "AST",
        level: 30,
        duration: 0,
        cooldown: 0,
        type: "RaidBuff",
        icon: "https://xivapi.com/i/003000/003102.png",
        color: "--filter-light-gold",
        order: 0,
    },
    {
        id: 4401,
        name: "The Balance",
        name_cn: "太阳神之衡",
        name_de: "Waage",
        name_en: "the Balance",
        name_fr: "La Balance",
        name_jp: "アーゼマの均衡",
        name_kr: "아제마의 균형",
        enabled: true,
        tts: true,
        ttstype: 2,
        job: "AST",
        level: 30,
        duration: 15,
        cooldown: 0,
        type: "RaidBuff",
        icon: "https://xivapi.com/i/003000/003110.png",
        color: "--filter-light-gold",
        order: 0,
        extra: {
            is_card: true,
        },
    },
    {
        id: 4402,
        name: "The Arrow",
        name_cn: "放浪神之箭",
        name_de: "Pfeil",
        name_en: "the Arrow",
        name_fr: "La Flèche",
        name_jp: "オシュオンの矢",
        name_kr: "오쉬온의 화살",
        enabled: true,
        tts: true,
        ttstype: 2,
        job: "AST",
        level: 30,
        duration: 15,
        cooldown: 0,
        type: "RaidBuff",
        icon: "https://xivapi.com/i/003000/003112.png",
        color: "--filter-light-gold",
        order: 0,
        extra: {
            is_card: true,
        },
    },
    {
        id: 4403,
        name: "The Spear",
        name_cn: "战争神之枪",
        name_de: "Speer",
        name_en: "the Spear",
        name_fr: "L'Épieu",
        name_jp: "ハルオーネの槍",
        name_kr: "할로네의 창",
        enabled: true,
        tts: true,
        ttstype: 2,
        job: "AST",
        level: 30,
        duration: 15,
        cooldown: 0,
        type: "RaidBuff",
        icon: "https://xivapi.com/i/003000/003113.png",
        color: "--filter-light-gold",
        order: 0,
        extra: {
            is_card: true,
        },
    },
    {
        id: 4404,
        name: "The Bole",
        name_cn: "世界树之干",
        name_de: "Eiche",
        name_en: "the Bole",
        name_fr: "Le Tronc",
        name_jp: "世界樹の幹",
        name_kr: "세계수의 줄기",
        enabled: true,
        tts: true,
        ttstype: 2,
        job: "AST",
        level: 30,
        duration: 15,
        cooldown: 0,
        type: "RaidBuff",
        icon: "https://xivapi.com/i/003000/003111.png",
        color: "--filter-light-gold",
        order: 0,
        extra: {
            is_card: true,
        },
    },
    {
        id: 4405,
        name: "The Ewer",
        name_cn: "河流神之瓶",
        name_de: "Krug",
        name_en: "the Ewer",
        name_fr: "L'Aiguière",
        name_jp: "サリャクの水瓶",
        name_kr: "살리아크의 물병",
        enabled: true,
        tts: true,
        ttstype: 2,
        job: "AST",
        level: 30,
        duration: 15,
        cooldown: 0,
        type: "RaidBuff",
        icon: "https://xivapi.com/i/003000/003114.png",
        color: "--filter-light-gold",
        order: 0,
        extra: {
            is_card: true,
        },
    },
    {
        id: 4406,
        name: "The Spire",
        name_cn: "建筑神之塔",
        name_de: "Turm",
        name_en: "the Spire",
        name_fr: "La Tour",
        name_jp: "ビエルゴの塔",
        name_kr: "비레고의 탑",
        enabled: true,
        tts: true,
        ttstype: 2,
        job: "AST",
        level: 30,
        duration: 15,
        cooldown: 0,
        type: "RaidBuff",
        icon: "https://xivapi.com/i/003000/003115.png",
        color: "--filter-light-gold",
        order: 0,
        extra: {
            is_card: true,
        },
    },
    {
        id: 7444,
        name: "Lord of Crowns",
        name_cn: "王冠之领主",
        name_de: "König der Kronen",
        name_en: "Lord of Crowns",
        name_fr: "Roi des couronnes",
        name_jp: "クラウンロード",
        name_kr: "왕의 검",
        enabled: true,
        tts: true,
        ttstype: 2,
        job: "AST",
        level: 50,
        duration: 15,
        cooldown: 0,
        type: "RaidBuff",
        icon: "https://xivapi.com/i/003000/003147.png",
        color: "--filter-light-gold",
        order: 0,
        extra: {
            is_card: true,
        },
    },
    {
        id: 7445,
        name: "Lady of Crowns",
        name_cn: "王冠之贵妇",
        name_de: "Königin der Kronen",
        name_en: "Lady of Crowns",
        name_fr: "Reine des couronnes",
        name_jp: "クラウンレディ",
        name_kr: "여왕의 날개",
        enabled: true,
        tts: true,
        ttstype: 2,
        job: "AST",
        level: 50,
        duration: 15,
        cooldown: 0,
        type: "RaidBuff",
        icon: "https://xivapi.com/i/003000/003146.png",
        color: "--filter-light-gold",
        order: 0,
        extra: {
            is_card: true,
        },
    },
    // BLM
    // DoTs
    {
        id: 161,
        name: "Thunder",
        name_cn: "闪雷",
        name_de: "Blitz",
        name_en: "Thunder",
        name_fr: "Foudre",
        name_jp: "サンダー",
        name_kr: "선더",
        enabled: true,
        tts: true,
        ttstype: 1,
        job: "BLM",
        type: "DoT",
        icon: "https://xivapi.com/i/010000/010457.png",
        color: "--filter-light-blue",
        order: 0,
        extra: {
            shares_cooldown: 163,
        },
    },
    {
        id: 162,
        name: "Thunder II",
        name_cn: "震雷",
        name_de: "Blitzra",
        name_en: "Thunder II",
        name_fr: "Extra Foudre",
        name_jp: "サンダラ",
        name_kr: "선더라",
        enabled: true,
        tts: true,
        ttstype: 1,
        job: "BLM",
        type: "DoT",
        icon: "https://xivapi.com/i/010000/010458.png",
        color: "--filter-light-blue",
        order: 0,
        extra: {
            shares_cooldown: 163,
        },
    },
    {
        id: 163,
        name: "Thunder III",
        name_cn: "暴雷",
        name_de: "Blitzga",
        name_en: "Thunder III",
        name_fr: "Méga Foudre",
        name_jp: "サンダガ",
        name_kr: "선더가",
        enabled: true,
        tts: true,
        ttstype: 1,
        job: "BLM",
        type: "DoT",
        icon: "https://xivapi.com/i/010000/010459.png",
        color: "--filter-light-blue",
        order: 0,
    },
    {
        id: 1210,
        name: "Thunder IV",
        name_cn: "霹雷",
        name_de: "Blitzka",
        name_en: "Thunder IV",
        name_fr: "Giga Foudre",
        name_jp: "サンダジャ",
        name_kr: "선더쟈",
        enabled: true,
        tts: true,
        ttstype: 1,
        job: "BLM",
        type: "DoT",
        icon: "https://xivapi.com/i/012000/012657.png",
        color: "--filter-light-blue",
        order: 0,
        extra: {
            shares_cooldown: 163,
        },
    },
    // Self-Buffs
    {
        id: 737,
        name: "Ley Lines",
        name_cn: "黑魔纹",
        name_de: "Ley-Linien",
        name_en: "Ley Lines",
        name_fr: "Manalignements",
        name_jp: "黒魔紋",
        name_kr: "흑마법 문양",
        enabled: true,
        tts: true,
        ttstype: 1,
        job: "BLM",
        type: "Buff",
        icon: "https://xivapi.com/i/012000/012653.png",
        color: "--filter-fuchsia",
        order: 0,
    },
    {
        id: 165,
        name: "Firestarter",
        name_cn: "火苗",
        name_de: "Feuga +",
        name_en: "Firestarter",
        name_fr: "Pyromane",
        name_jp: "ファイガ効果アップ",
        name_kr: "파이가 효과 향상",
        enabled: true,
        tts: true,
        ttstype: 2,
        job: "BLM",
        type: "Buff",
        icon: "https://xivapi.com/i/010000/010460.png",
        color: "--filter-bright-red",
        order: 1,
    },
    {
        id: 1365,
        name: "Thundercloud",
        name_cn: "雷云",
        name_de: "Blitzga-bereit",
        name_en: "Thundercloud",
        name_fr: "Nuage d'orage",
        name_jp: "サンダー系魔法効果アップ",
        name_kr: "선더 계열 효과 향상",
        enabled: true,
        tts: true,
        ttstype: 2,
        job: "BLM",
        type: "Buff",
        icon: "https://xivapi.com/i/010000/010461.png",
        color: "--filter-dark-blue",
        order: 2,
    },
    // BLU
    // Dots
    {
        id: 1714,
        name: "Bleeding", // Song of Torment & Nightbloom
        name_cn: "出血",
        name_de: "Blutung",
        name_en: "Bleeding",
        name_fr: "Saignement",
        name_jp: "ペイン",
        name_kr: "고통",
        enabled: true,
        tts: true,
        ttstype: 1,
        job: "BLU",
        type: "DoT",
        icon: "https://xivapi.com/i/013000/013501.png",
        color: "--filter-dark-red",
        order: 0,
    },
    // Self-Buffs
    {
        id: 1718,
        name: "Waxing Nocturne", // Moonflute Buff
        name_cn: "狂战士化",
        name_de: "Ekstatischer Kampf",
        name_en: "Waxing Nocturne",
        name_fr: "Forcené",
        name_jp: "狂戦士化",
        name_kr: "광전사화",
        enabled: true,
        tts: true,
        ttstype: 1,
        job: "BLU",
        type: "Buff",
        icon: "https://xivapi.com/i/013000/013505.png",
        color: "--filter-light-gold",
        order: 0,
    },
    {
        id: 1727,
        name: "Waning Nocturne", // Moonflute Debuff
        name_cn: "狂战士化的副作用",
        name_de: "Ermüdung des ekstatischen Kampfes",
        name_en: "Waning Nocturne",
        name_fr: "Contrecoup du forcené",
        name_jp: "狂戦士化の反動",
        name_kr: "광전사화 반동",
        enabled: true,
        tts: true,
        ttstype: 1,
        job: "BLU",
        type: "Buff",
        icon: "https://xivapi.com/i/013000/013512.png",
        color: "--filter-dark-blue",
        order: 0,
        extra: {
            shares_cooldown: 1718,
        },
    },
    // BRD
    // DoTs
    {
        id: 124,
        name: "Venomous Bite",
        name_cn: "毒咬箭",
        name_de: "Infizierte Wunde",
        name_en: "Venomous Bite",
        name_fr: "Morsure venimeuse",
        name_jp: "ベノムバイト",
        name_kr: "독화살",
        enabled: true,
        tts: true,
        ttstype: 1,
        job: "BRD",
        type: "DoT",
        icon: "https://xivapi.com/i/010000/010352.png",
        color: "--filter-light-pink",
        order: 0,
    },
    {
        id: 129,
        name: "Windbite",
        name_cn: "风蚀箭",
        name_de: "Beißender Wind",
        name_en: "Windbite",
        name_fr: "Morsure du vent",
        name_jp: "ウィンドバイト",
        name_kr: "바람 화살",
        enabled: true,
        tts: true,
        ttstype: 1,
        job: "BRD",
        type: "DoT",
        icon: "https://xivapi.com/i/010000/010360.png",
        color: "--filter-baby-blue",
        order: 1,
    },
    {
        id: 1200,
        name: "Caustic Bite",
        name_cn: "烈毒咬箭",
        name_de: "Kaustischer Biss",
        name_en: "Caustic Bite",
        name_fr: "Morsure caustique",
        name_jp: "コースティックバイト",
        name_kr: "맹독 화살",
        enabled: true,
        tts: true,
        ttstype: 1,
        job: "BRD",
        type: "DoT",
        icon: "https://xivapi.com/i/012000/012616.png",
        color: "--filter-light-pink",
        order: 0,
    },
    {
        id: 1201,
        name: "Stormbite",
        name_cn: "狂风蚀箭",
        name_de: "Sturmbiss",
        name_en: "Stormbite",
        name_fr: "Morsure de la tempête",
        name_jp: "ストームバイト",
        name_kr: "폭풍 화살",
        enabled: true,
        tts: true,
        ttstype: 1,
        job: "BRD",
        type: "DoT",
        icon: "https://xivapi.com/i/012000/012617.png",
        color: "--filter-baby-blue",
        order: 1,
    },
    // Self-Buffs
    {
        id: 125,
        name: "Raging Strikes",
        name_cn: "猛者强击",
        name_de: "Wütende Attacke",
        name_en: "Raging Strikes",
        name_fr: "Tir furieux",
        name_jp: "猛者の撃",
        name_kr: "용맹한 사격",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "BRD",
        type: "Buff",
        icon: "https://xivapi.com/i/010000/010354.png",
        color: "--filter-dark-red",
        order: 0,
    },
    // Raid Buffs
    {
        id: 118,
        name: "Battle Voice",
        name_cn: "战斗之声",
        name_de: "Ode an die Seele",
        name_en: "Battle Voice",
        name_fr: "Voix de combat",
        name_jp: "バトルボイス",
        name_kr: "전장의 노래",
        enabled: true,
        tts: true,
        ttstype: 2,
        job: "BRD",
        level: 50,
        duration: 20,
        cooldown: 180,
        type: "RaidBuff",
        icon: "https://xivapi.com/i/002000/002601.png",
        color: "--filter-dark-red",
        order: 0,
    },
    {
        id: 17056,
        name: "Song",
        name_cn: "歌",
        name_de: "Lied",
        name_en: "Song",
        name_fr: "Chanson",
        name_jp: "歌",
        name_kr: "노래",
        enabled: true,
        tts: false,
        ttstype: 0,
        job: "BRD",
        level: 30,
        duration: 5,
        cooldown: 0,
        type: "RaidBuff",
        icon: "https://xivapi.com/i/005000/005315.png",
        color: "--filter-light-gold",
        order: 0,
    },
    {
        id: 3559,
        name: "the Wanderer's Minuet",
        name_cn: "放浪神的小步舞曲",
        name_de: "Menuett des Wanderers",
        name_en: "the Wanderer's Minuet",
        name_fr: "Menuet du Vagabond",
        name_jp: "旅神のメヌエット",
        name_kr: "여행신의 무곡",
        enabled: true,
        tts: false,
        ttstype: 0,
        job: "BRD",
        level: 52,
        duration: 30,
        cooldown: 0,
        type: "RaidBuff",
        icon: "https://xivapi.com/i/002000/002607.png",
        color: "--filter-dark-red",
        order: 0,
        extra: {
            is_song: true,
        },
    },
    {
        id: 114,
        name: "Mage's Ballad",
        name_cn: "贤者的叙事谣",
        name_de: "Ballade des Weisen",
        name_en: "Mage's Ballad",
        name_fr: "Ballade du mage",
        name_jp: "賢人のバラード",
        name_kr: "현자의 담시곡",
        enabled: true,
        tts: false,
        ttstype: 0,
        job: "BRD",
        level: 30,
        duration: 30,
        cooldown: 0,
        type: "RaidBuff",
        icon: "https://xivapi.com/i/002000/002602.png",
        color: "--filter-dark-red",
        order: 0,
        extra: {
            is_song: true,
        },
    },
    {
        id: 116,
        name: "Army's Paeon",
        name_cn: "军神的赞美歌",
        name_de: "Hymne der Krieger",
        name_en: "Army's Paeon",
        name_fr: "Péan martial",
        name_jp: "軍神のパイオン",
        name_kr: "군신의 찬가",
        enabled: true,
        tts: false,
        ttstype: 0,
        job: "BRD",
        level: 40,
        duration: 30,
        cooldown: 0,
        type: "RaidBuff",
        icon: "https://xivapi.com/i/002000/002603.png",
        color: "--filter-dark-red",
        order: 0,
        extra: {
            is_song: true,
        },
    },
    // Party Cooldowns
    {
        id: 7405,
        name: "Troubadour",
        name_cn: "行吟",
        name_de: "Troubadour",
        name_en: "Troubadour",
        name_fr: "Troubadour",
        name_jp: "トルバドゥール",
        name_kr: "방랑하는 음악가",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "BRD",
        level: 62,
        duration: 15,
        cooldown: 120,
        type: "Party",
        icon: "https://xivapi.com/i/002000/002612.png",
        color: "--filter-dark-red",
        order: 0,
    },
    // DNC
    // Self-Buffs
    {
        id: 1825,
        name: "Devilment",
        name_cn: "进攻之探戈",
        name_de: "Todestango",
        name_en: "Devilment",
        name_fr: "Tango endiablé",
        name_jp: "攻めのタンゴ",
        name_kr: "공세의 탱고",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "DNC",
        type: "Buff",
        icon: "https://xivapi.com/i/013000/013714.png",
        color: "--filter-dark-green",
        order: 4,
    },
    {
        id: 1827,
        name: "Improvisation",
        name_cn: "即兴表演",
        name_de: "Tanzimprovisation",
        name_en: "Improvisation",
        name_fr: "Improvisation",
        name_jp: "インプロビゼーション",
        name_kr: "즉흥 연기",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "DNC",
        type: "Buff",
        icon: "https://xivapi.com/i/013000/013716.png",
        color: "--filter-jungle-green",
        order: 3,
    },
    {
        id: 1821,
        name: "Standard Finish",
        name_cn: "标准舞步结束",
        name_de: "Einfaches Finale",
        name_en: "Standard Finish",
        name_fr: "Final classique",
        name_jp: "スタンダードフィニッシュ",
        name_kr: "정석 마무리",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "DNC",
        type: "Buff",
        icon: "https://xivapi.com/i/013000/013708.png",
        color: "--filter-green-blue",
        order: 1,
    },
    {
        id: 1822,
        name: "Technical Finish",
        name_cn: "技巧舞步结束",
        name_de: "Komplexes Finale",
        name_en: "Technical Finish",
        name_fr: "Final technique",
        name_jp: "テクニカルフィニッシュ",
        name_kr: "기교 마무리",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "DNC",
        type: "Buff",
        icon: "https://xivapi.com/i/013000/013709.png",
        color: "--filter-bright-red",
        order: 2,
    },
    // Raid Buffs
    {
        id: 16011,
        name: "Devilment",
        name_cn: "进攻之探戈",
        name_de: "Todestango",
        name_en: "Devilment",
        name_fr: "Tango endiablé",
        name_jp: "攻めのタンゴ",
        name_kr: "공세의 탱고",
        enabled: true,
        tts: true,
        ttstype: 2,
        job: "DNC",
        level: 62,
        duration: 20,
        cooldown: 120,
        type: "RaidBuff",
        icon: "https://xivapi.com/i/003000/003471.png",
        color: "--filter-dark-red",
        order: 0,
    },
    {
        id: 15997,
        name: "Standard Step",
        name_cn: "标准舞步",
        name_de: "Einfache Choreographie",
        name_en: "Standard Step",
        name_fr: "Pas classique",
        name_jp: "スタンダードステップ",
        name_kr: "정석 무도",
        enabled: true,
        tts: false,
        ttstype: 2,
        job: "DNC",
        level: 15,
        duration: 0,
        cooldown: 30,
        type: "RaidBuff",
        icon: "https://xivapi.com/i/003000/003459.png",
        color: "--filter-dark-red",
        order: 0,
        extra: {
            cooldown_only: true,
        },
    },
    {
        id: 16191,
        name: "Single Standard Finish",
        name_cn: "单色标准舞步结束",
        name_de: "Einfaches Finale I",
        name_en: "Single Standard Finish",
        name_fr: "Final classique simple",
        name_jp: "シングル・スタンダードフィニッシュ",
        name_kr: "정석 마무리 1단계",
        enabled: true,
        tts: false,
        ttstype: 2,
        job: "DNC",
        level: 15,
        duration: 60,
        cooldown: 30,
        type: "RaidBuff",
        icon: "https://xivapi.com/i/003000/003459.png",
        color: "--filter-dark-red",
        order: 0,
        extra: {
            is_ss: true,
            status: 1,
            status_text: "Single",
        },
    },
    {
        id: 16192,
        name: "Double Standard Finish",
        name_cn: "双色标准舞步结束",
        name_de: "Einfaches Finale II",
        name_en: "Double Standard Finish",
        name_fr: "Final classique doublé",
        name_jp: "ダブル・スタンダードフィニッシュ",
        name_kr: "정석 마무리 2단계",
        enabled: true,
        tts: false,
        ttstype: 2,
        job: "DNC",
        level: 15,
        duration: 60,
        cooldown: 30,
        type: "RaidBuff",
        icon: "https://xivapi.com/i/003000/003459.png",
        color: "--filter-dark-red",
        order: 0,
        extra: {
            is_ss: true,
            status: 0,
            status_text: "Double",
        },
    },
    {
        id: 16003,
        name: "Standard Step",
        name_cn: "标准舞步",
        name_de: "Einfache Choreographie",
        name_en: "Standard Step",
        name_fr: "Pas classique",
        name_jp: "スタンダードステップ",
        name_kr: "정석 무도",
        enabled: true,
        tts: false,
        ttstype: 2,
        job: "DNC",
        level: 15,
        duration: 60,
        cooldown: 30,
        type: "RaidBuff",
        icon: "https://xivapi.com/i/003000/003459.png",
        color: "--filter-dark-red",
        order: 0,
        extra: {
            is_ss: true,
            status: 1,
            status_text: "Failed",
        },
    },
    {
        id: 15998,
        name: "Technical Step",
        name_cn: "技巧舞步",
        name_de: "Komplexe Choreographie",
        name_en: "Technical Step",
        name_fr: "Pas technique",
        name_jp: "テクニカルステップ",
        name_kr: "기교 마무리",
        enabled: true,
        tts: true,
        ttstype: 2,
        job: "DNC",
        level: 70,
        duration: 20,
        cooldown: 120,
        type: "RaidBuff",
        icon: "https://xivapi.com/i/003000/003474.png",
        color: "--filter-dark-red",
        order: 0,
        extra: {
            cooldown_only: true,
        },
    },
    {
        id: 16004,
        name: "Technical Step",
        name_cn: "技巧舞步",
        name_de: "Komplexe Choreographie",
        name_en: "Technical Step",
        name_fr: "Pas technique",
        name_jp: "テクニカルステップ",
        name_kr: "기교 마무리",
        enabled: true,
        tts: true,
        ttstype: 2,
        job: "DNC",
        level: 70,
        duration: 20,
        cooldown: 120,
        type: "RaidBuff",
        icon: "https://xivapi.com/i/003000/003474.png",
        color: "--filter-dark-red",
        order: 0,
        extra: {
            is_ts: true,
            status: 0,
            status_text: "Failed",
        },
    },
    {
        id: 16193,
        name: "Single Technical Finish",
        name_cn: "单色技巧舞步结束",
        name_de: "Komplexes Finale I",
        name_en: "Single Technical Finish",
        name_fr: "Final technique simple",
        name_jp: "シングル・テクニカルフィニッシュ",
        name_kr: "기교 마무리 1단계",
        enabled: true,
        tts: true,
        ttstype: 2,
        job: "DNC",
        level: 70,
        duration: 20,
        cooldown: 120,
        type: "RaidBuff",
        icon: "https://xivapi.com/i/003000/003474.png",
        color: "--filter-dark-red",
        order: 0,
        extra: {
            is_ts: true,
            status: 0,
            status_text: "Single",
        },
    },
    {
        id: 16194,
        name: "Double Technical Finish",
        name_cn: "双色技巧舞步结束",
        name_de: "Komplexes Finale II",
        name_en: "Double Technical Finish",
        name_fr: "Final technique doublé",
        name_jp: "ダブル・テクニカルフィニッシュ",
        name_kr: "기교 마무리 2단계",
        enabled: true,
        tts: true,
        ttstype: 2,
        job: "DNC",
        level: 70,
        duration: 20,
        cooldown: 120,
        type: "RaidBuff",
        icon: "https://xivapi.com/i/003000/003474.png",
        color: "--filter-dark-red",
        order: 0,
        extra: {
            is_ts: true,
            status: 0,
            status_text: "Double",
        },
    },
    {
        id: 16195,
        name: "Triple Technical Finish",
        name_cn: "技巧舞步",
        name_de: "Komplexes Finale III",
        name_en: "Triple Technical Finish",
        name_fr: "Final technique triplé",
        name_jp: "トリプル・テクニカルフィニッシュ",
        name_kr: "기교 마무리 3단계",
        enabled: true,
        tts: true,
        ttstype: 2,
        job: "DNC",
        level: 70,
        duration: 20,
        cooldown: 120,
        type: "RaidBuff",
        icon: "https://xivapi.com/i/003000/003474.png",
        color: "--filter-dark-red",
        order: 0,
        extra: {
            is_ts: true,
            status: 0,
            status_text: "Triple",
        },
    },
    {
        id: 16196,
        name: "Quadruple Technical Finish",
        name_cn: "四色技巧舞步结束",
        name_de: "Komplexes Finale IV",
        name_en: "Quadruple Technical Finish",
        name_fr: "Final technique quadruplé",
        name_jp: "クワッド・テクニカルフィニッシュ",
        name_kr: "기교 마무리 4단계",
        enabled: true,
        tts: true,
        ttstype: 2,
        job: "DNC",
        level: 70,
        duration: 20,
        cooldown: 120,
        type: "RaidBuff",
        icon: "https://xivapi.com/i/003000/003474.png",
        color: "--filter-dark-red",
        order: 0,
        extra: {
            is_ts: true,
            status: 1,
            status_text: "Quadruple",
        },
    },
    // Party Cooldowns
    {
        id: 16012,
        name: "Shield Samba",
        name_cn: "防守之桑巴",
        name_de: "Schildsamba",
        name_en: "Shield Samba",
        name_fr: "Samba protectrice",
        name_jp: "守りのサンバ",
        name_kr: "수세의 삼바",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "DNC",
        level: 56,
        duration: 15,
        cooldown: 120,
        type: "Party",
        icon: "https://xivapi.com/i/003000/003469.png",
        color: "--filter-light-purple",
        order: 0,
    },
    // DRG
    // DoTs
    {
        id: 118,
        name: "Chaos Thrust",
        name_cn: "樱花怒放",
        name_de: "Chaotischer Tjost",
        name_en: "Chaos Thrust",
        name_fr: "Percée chaotique",
        name_jp: "桜華狂咲",
        name_kr: "꽃잎 폭풍",
        enabled: true,
        tts: true,
        ttstype: 1,
        job: "DRG",
        type: "DoT",
        icon: "https://xivapi.com/i/010000/010307.png",
        color: "--filter-light-purple",
        order: 0,
    },
    // Self-Buffs
    {
        id: 121,
        name: "Disembowel",
        name_cn: "开膛枪",
        name_de: "Drachengriff",
        name_en: "Disembowel",
        name_fr: "Éventration",
        name_jp: "ディセムボウル",
        name_kr: "몸통 가르기",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "DRG",
        type: "Buff",
        icon: "https://xivapi.com/i/012000/012576.png",
        color: "--filter-grey",
        order: 0,
    },
    {
        id: 1183,
        name: "Dragon Sight",
        name_cn: "巨龙视线",
        name_de: "Drachenblick",
        name_en: "Dragon Sight",
        name_fr: "Vue de dragon",
        name_jp: "ドラゴンサイト",
        name_kr: "용의 오른눈",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "DRG",
        type: "Buff",
        icon: "https://xivapi.com/i/012000/012581.png",
        color: "--filter-dark-red",
        order: 1,
    },
    {
        id: 1864,
        name: "Lance Charge",
        name_cn: "猛枪",
        name_de: "Lanzenschärfung",
        name_en: "Lance Charge",
        name_fr: "Lance acérée",
        name_jp: "ランスチャージ",
        name_kr: "돌격하는 창",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "DRG",
        type: "Buff",
        icon: "https://xivapi.com/i/010000/010304.png",
        color: "--filter-dark-red",
        order: 2,
    },
    // Raid Buffs
    {
        id: 3557,
        name: "Battle Litany",
        name_cn: "战斗连祷",
        name_de: "Litanei der Schlacht",
        name_en: "Battle Litany",
        name_fr: "Litanie combattante",
        name_jp: "バトルリタニー",
        name_kr: "전투 기도",
        enabled: true,
        tts: true,
        ttstype: 2,
        job: "DRG",
        level: 52,
        duration: 20,
        cooldown: 180,
        type: "RaidBuff",
        icon: "https://xivapi.com/i/002000/002585.png",
        color: "--filter-dark-red",
        order: 0,
    },
    {
        id: 7398,
        name: "Dragon Sight",
        name_cn: "巨龙视线",
        name_de: "Drachenblick",
        name_en: "Dragon Sight",
        name_fr: "Vue de dragon",
        name_jp: "ドラゴンサイト",
        name_kr: "용의 오른눈",
        enabled: true,
        tts: true,
        ttstype: 2,
        job: "DRG",
        level: 66,
        duration: 20,
        cooldown: 120,
        type: "RaidBuff",
        icon: "https://xivapi.com/i/002000/002587.png",
        color: "--filter-dark-red",
        order: 0,
    },
    // DRK
    // Buffs
    {
        id: 742,
        name: "Blood Weapon",
        name_cn: "嗜血",
        name_de: "Blutwaffe",
        name_en: "Blood Weapon",
        name_fr: "Arme de sang",
        name_jp: "ブラッドウェポン",
        name_kr: "피의 칼날",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "DRK",
        type: "Buff",
        icon: "https://xivapi.com/i/013000/013109.png",
        color: "--filter-dark-red",
        order: 0,
    },
    {
        id: 1972,
        name: "Delirium",
        name_cn: "血乱",
        name_de: "Blutdelirium",
        name_en: "Delirium",
        name_fr: "Delirium de sang",
        name_jp: "ブラッドデリリアム",
        name_kr: "피의 열광",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "DRK",
        type: "Buff",
        icon: "https://xivapi.com/i/013000/013121.png",
        color: "--filter-bright-red",
        order: 1,
    },
    // Mitigation
    {
        id: 3634,
        name: "Dark Mind",
        name_cn: "弃明投暗",
        name_de: "Dunkler Geist",
        name_en: "Dark Mind",
        name_fr: "Esprit ténébreux",
        name_jp: "ダークマインド",
        name_kr: "어두운 감정",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "DRK",
        level: 45,
        duration: 10,
        cooldown: 60,
        type: "Mitigation",
        icon: "https://xivapi.com/i/003000/003076.png",
        color: "--filter-light-blue",
        order: 0,
    },
    {
        id: 3636,
        name: "Shadow Wall",
        name_cn: "暗影墙",
        name_de: "Schattenwand",
        name_en: "Shadow Wall",
        name_fr: "Mur d'ombre",
        name_jp: "シャドウウォール",
        name_kr: "그림자 장벽",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "DRK",
        level: 38,
        duration: 15,
        cooldown: 120,
        type: "Mitigation",
        icon: "https://xivapi.com/i/003000/003075.png",
        color: "--filter-light-blue",
        order: 1,
    },
    {
        id: 7393,
        name: "The Blackest Night",
        name_cn: "至黑之夜",
        name_de: "Schwärzeste Nacht",
        name_en: "The Blackest Night",
        name_fr: "Nuit noirissime",
        name_jp: "ブラックナイト",
        name_kr: "흑야",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "DRK",
        level: 70,
        duration: 7,
        cooldown: 15,
        type: "Mitigation",
        icon: "https://xivapi.com/i/003000/003081.png",
        color: "--filter-light-blue",
        order: 2,
    },
    {
        id: 16471,
        name: "Dark Missionary",
        name_cn: "暗黑布道",
        name_de: "Dunkler Bote",
        name_en: "Dark Missionary",
        name_fr: "Missionnaire des Ténèbres",
        name_jp: "ダークミッショナリー",
        name_kr: "어둠의 포교자",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "DRK",
        level: 76,
        duration: 15,
        cooldown: 90,
        type: "Mitigation",
        icon: "https://xivapi.com/i/003000/003087.png",
        color: "--filter-light-blue",
        order: 3,
    },
    {
        id: 3638,
        name: "Living Dead",
        name_cn: "行尸走肉",
        name_de: "Totenerweckung",
        name_en: "Living Dead",
        name_fr: "Mort-vivant",
        name_jp: "リビングデッド",
        name_kr: "컴버가",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "DRK",
        level: 50,
        duration: 10,
        cooldown: 300,
        type: "Mitigation",
        icon: "https://xivapi.com/i/003000/003077.png",
        color: "--filter-light-blue",
        order: 4,
    },
    // Party Cooldowns
    {
        id: 3638,
        name: "Living Dead",
        name_cn: "行尸走肉",
        name_de: "Totenerweckung",
        name_en: "Living Dead",
        name_fr: "Mort-vivant",
        name_jp: "リビングデッド",
        name_kr: "산송장",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "DRK",
        level: 50,
        duration: 10,
        cooldown: 300,
        type: "Party",
        icon: "https://xivapi.com/i/003000/003077.png",
        color: "--filter-light-blue",
        order: 0,
    },
    {
        id: 16471,
        name: "Dark Missionary",
        name_cn: "暗黑布道",
        name_de: "Dunkler Bote",
        name_en: "Dark Missionary",
        name_fr: "Missionnaire des Ténèbres",
        name_jp: "ダークミッショナリー",
        name_kr: "어둠의 포교자",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "DRK",
        level: 76,
        duration: 15,
        cooldown: 90,
        type: "Party",
        icon: "https://xivapi.com/i/003000/003087.png",
        color: "--filter-light-blue",
        order: 1,
    },
    // GNB
    // DoTs
    {
        id: 1837,
        name: "Sonic Break",
        name_cn: "音速破",
        name_de: "Schallbrecher",
        name_en: "Sonic Break",
        name_fr: "Rupture sonique",
        name_jp: "ソニックブレイク",
        name_kr: "음속 파괴",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "GNB",
        type: "DoT",
        icon: "https://xivapi.com/i/013000/013607.png",
        color: "--filter-light-blue",
        order: 0,
    },
    {
        id: 1838,
        name: "Bow Shock",
        name_cn: "弓形冲波",
        name_de: "Schockpatrone",
        name_en: "Bow Shock",
        name_fr: "Arc de choc",
        name_jp: "バウショック",
        name_kr: "원형충격파",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "GNB",
        type: "DoT",
        icon: "https://xivapi.com/i/013000/013608.png",
        color: "--filter-light-gold",
        order: 1,
    },
    // Buffs
    {
        id: 1831,
        name: "No Mercy",
        name_cn: "无情",
        name_de: "Ohne Gnade",
        name_en: "No Mercy",
        name_fr: "Sans pitié",
        name_jp: "ノー・マーシー",
        name_kr: "무자비",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "GNB",
        type: "Buff",
        icon: "https://xivapi.com/i/013000/013601.png",
        color: "--filter-light-blue",
        order: 0,
    },
    // Mitigation
    {
        id: 16161,
        name: "Heart of Stone",
        name_cn: "石之心",
        name_de: "Steinernes Herz",
        name_en: "Heart of Stone",
        name_fr: "Cœur de pierre",
        name_jp: "ハート・オブ・ストーン",
        name_kr: "돌의 심장",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "GNB",
        level: 68,
        duration: 7,
        cooldown: 25,
        type: "Mitigation",
        icon: "https://xivapi.com/i/003000/003425.png",
        color: "--filter-light-blue",
        order: 0,
    },
    {
        id: 16151,
        name: "Aurora",
        name_cn: "极光",
        name_de: "Aurora",
        name_en: "Aurora",
        name_fr: "Aurore",
        name_jp: "オーロラ",
        name_kr: "오로라",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "GNB",
        level: 68,
        duration: 18,
        cooldown: 60,
        type: "Mitigation",
        icon: "https://xivapi.com/i/003000/003415.png",
        color: "--filter-light-blue",
        order: 1,
    },
    {
        id: 16140,
        name: "Camouflage",
        name_cn: "伪装",
        name_de: "Camouflage",
        name_en: "Camouflage",
        name_fr: "Camouflage",
        name_jp: "カモフラージュ",
        name_kr: "위장술",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "GNB",
        level: 6,
        duration: 20,
        cooldown: 90,
        type: "Mitigation",
        icon: "https://xivapi.com/i/003000/003404.png",
        color: "--filter-light-blue",
        order: 2,
    },
    {
        id: 16148,
        name: "Nebula",
        name_cn: "星云",
        name_de: "Nebula",
        name_en: "Nebula",
        name_fr: "Nébuleuse",
        name_jp: "ネビュラ",
        name_kr: "성운",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "GNB",
        level: 38,
        duration: 15,
        cooldown: 120,
        type: "Mitigation",
        icon: "https://xivapi.com/i/003000/003412.png",
        color: "--filter-light-blue",
        order: 3,
    },
    {
        id: 16160,
        name: "Heart of Light",
        name_cn: "光之心",
        name_de: "Wackeres Herz",
        name_en: "Heart of Light",
        name_fr: "Cœur de Lumière",
        name_jp: "ハート・オブ・ライト",
        name_kr: "빛의 심장",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "GNB",
        level: 64,
        duration: 15,
        cooldown: 90,
        type: "Mitigation",
        icon: "https://xivapi.com/i/003000/003424.png",
        color: "--filter-light-blue",
        order: 4,
    },
    {
        id: 16152,
        name: "Superbolide",
        name_cn: "超火流星",
        name_de: "Meteoritenfall",
        name_en: "Superbolide",
        name_fr: "Bolide",
        name_jp: "ボーライド",
        name_kr: "폭발 유성",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "GNB",
        level: 50,
        duration: 8,
        cooldown: 360,
        type: "Mitigation",
        icon: "https://xivapi.com/i/003000/003416.png",
        color: "--filter-light-blue",
        order: 5,
    },
    // Party Cooldowns
    {
        id: 16152,
        name: "Superbolide",
        name_cn: "超火流星",
        name_de: "Meteoritenfall",
        name_en: "Superbolide",
        name_fr: "Bolide",
        name_jp: "ボーライド",
        name_kr: "폭발 유성",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "GNB",
        level: 50,
        duration: 8,
        cooldown: 360,
        type: "Party",
        icon: "https://xivapi.com/i/003000/003416.png",
        color: "--filter-light-blue",
        order: 0,
    },
    {
        id: 16160,
        name: "Heart of Light",
        name_cn: "光之心",
        name_de: "Wackeres Herz",
        name_en: "Heart of Light",
        name_fr: "Cœur de Lumière",
        name_jp: "ハート・オブ・ライト",
        name_kr: "빛의 심장",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "GNB",
        level: 64,
        duration: 15,
        cooldown: 90,
        type: "Party",
        icon: "https://xivapi.com/i/003000/003424.png",
        color: "--filter-light-blue",
        order: 1,
    },
    // MCH
    // DoTs
    {
        id: 1866,
        name: "Bioblaster",
        name_cn: "毒菌冲击",
        name_de: "Bioblaster",
        name_en: "Bioblaster",
        name_fr: "Lance-toxine",
        name_jp: "バイオブラスト",
        name_kr: "생화학무기",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "MCH",
        type: "DoT",
        icon: "https://xivapi.com/i/013000/013020.png",
        color: "--filter-toxic-green",
        order: 0,
    },
    // Buffs
    {
        id: 688,
        name: "Hypercharge",
        name_cn: "超荷",
        name_de: "Hyperladung",
        name_en: "Hypercharge",
        name_fr: "Hypercharge",
        name_jp: "ハイパーチャージ",
        name_kr: "과충전",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "MCH",
        type: "Buff",
        icon: "https://xivapi.com/i/013000/013012.png",
        color: "--filter-dark-green",
        order: 0,
    },
    {
        id: 1946,
        name: "Wildfire",
        name_cn: "野火",
        name_de: "Wildfeuer",
        name_en: "Wildfire",
        name_fr: "Flambée",
        name_jp: "ワイルドファイア",
        name_kr: "소이탄",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "MCH",
        type: "Buff",
        icon: "https://xivapi.com/i/013000/013019.png",
        color: "--filter-orange",
        order: 1,
    },
    // Party Cooldowns
    {
        id: 16889,
        name: "Tactician",
        name_cn: "野火",
        name_de: "Taktiker",
        name_en: "Tactician",
        name_fr: "Tacticien",
        name_jp: "タクティシャン",
        name_kr: "책략가",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "MCH",
        level: 56,
        duration: 15,
        cooldown: 120,
        type: "Party",
        icon: "https://xivapi.com/i/003000/003040.png",
        color: "--filter-orange",
        order: 0,
    },
    // MNK
    // DoTs
    {
        id: 246,
        name: "Demolish",
        name_cn: "破碎拳",
        name_de: "Demolieren",
        name_en: "Demolish",
        name_fr: "Démolition",
        name_jp: "破砕拳",
        name_kr: "파쇄권",
        enabled: true,
        tts: true,
        ttstype: 1,
        job: "MNK",
        type: "DoT",
        icon: "https://xivapi.com/i/010000/010218.png",
        color: "--filter-light-purple",
        order: 0,
    },
    // Buffs
    {
        id: 592,
        name: "Ring of Fire",
        name_cn: "火焰漩涡",
        name_de: "Flammenwand",
        name_en: "Ring of Fire",
        name_fr: "Vortex de feu",
        name_jp: "炎渦",
        name_kr: "불꽃의 소용돌이",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "MNK",
        type: "Buff",
        icon: "https://xivapi.com/i/015000/015628.png",
        color: "--filter-bright-red",
        order: 0,
    },
    {
        id: 101,
        name: "Twin Snakes",
        name_cn: "双掌打",
        name_de: "Doppelviper",
        name_en: "Twin Snakes",
        name_fr: "Serpents jumeaux",
        name_jp: "双掌打",
        name_kr: "쌍장타",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "MNK",
        type: "Buff",
        icon: "https://xivapi.com/i/010000/010216.png",
        color: "--filter-grey",
        order: 1,
    },
    {
        id: 1181,
        name: "Riddle Of Fire",
        name_cn: "红莲极意",
        name_de: "Flammendes Enigma",
        name_en: "Riddle of Fire",
        name_fr: "Énigme du feu",
        name_jp: "紅蓮の極意",
        name_kr: "홍련의 극의",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "MNK",
        type: "Buff",
        icon: "https://xivapi.com/i/012000/012528.png",
        color: "--filter-bright-red",
        order: 2,
    },
    // Raid Buffs
    {
        id: 7396,
        name: "Brotherhood",
        name_cn: "义结金兰",
        name_de: "Bruderschaft",
        name_en: "Brotherhood",
        name_fr: "Fraternité",
        name_jp: "桃園結義",
        name_kr: "도원결의",
        enabled: true,
        tts: true,
        ttstype: 2,
        job: "MNK",
        level: 70,
        duration: 15,
        cooldown: 90,
        type: "RaidBuff",
        icon: "https://xivapi.com/i/002000/002542.png",
        color: "--filter-dark-red",
        order: 0,
    },
    // NIN
    // DoTs
    {
        id: 508,
        name: "Shadow Fang",
        name_cn: "影牙",
        name_de: "Schattenfang",
        name_en: "Shadow Fang",
        name_fr: "Croc d'ombre",
        name_jp: "影牙",
        name_kr: "그림자 송곳니",
        enabled: true,
        tts: true,
        ttstype: 1,
        job: "NIN",
        type: "DoT",
        icon: "https://xivapi.com/i/010000/010612.png",
        color: "--filter-baby-blue",
        order: 0,
    },
    // Buffs
    {
        id: 500,
        name: "Huton",
        name_cn: "风遁之术",
        name_de: "Huton",
        name_en: "Huton",
        name_fr: "Fûton",
        name_jp: "風遁の術",
        name_kr: "풍둔술",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "NIN",
        type: "Buff",
        icon: "https://xivapi.com/i/012000/012903.png",
        color: "--filter-light-blue",
        order: 1,
    },
    // Raid Buffs
    {
        id: 2258,
        name: "Trick Attack",
        name_cn: "攻其不备",
        name_de: "Trickattacke",
        name_en: "Trick Attack",
        name_fr: "Attaque sournoise",
        name_jp: "だまし討ち",
        name_kr: "속임수 공격",
        enabled: true,
        tts: true,
        ttstype: 2,
        job: "NIN",
        level: 18,
        duration: 15,
        cooldown: 60,
        type: "RaidBuff",
        icon: "https://xivapi.com/i/000000/000618.png",
        color: "--filter-dark-red",
        order: 0,
    },
    // PLD
    // DoTs
    {
        id: 248,
        name: "Circle of Scorn",
        name_cn: "厄运流转",
        name_de: "Kreis der Verachtung",
        name_en: "Circle of Scorn",
        name_fr: "Cercle du destin",
        name_jp: "サークル・オブ・ドゥーム",
        name_kr: "파멸의 진",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "PLD",
        type: "DoT",
        icon: "https://xivapi.com/i/010000/010158.png",
        color: "--filter-orange",
        order: 0,
    },
    {
        id: 725,
        name: "Goring Blade",
        name_cn: "沥血剑",
        name_de: "Ausweiden",
        name_en: "Goring Blade",
        name_fr: "Lame étripante",
        name_jp: "ゴアブレード",
        name_kr: "꿰뚫는 검격",
        enabled: true,
        tts: true,
        ttstype: 1,
        job: "PLD",
        type: "DoT",
        icon: "https://xivapi.com/i/012000/012507.png",
        color: "--filter-orange",
        order: 1,
    },
    // Buffs
    {
        id: 76,
        name: "Fight or Flight",
        name_cn: "战逃反应",
        name_de: "Verwegenheit",
        name_en: "Fight or Flight",
        name_fr: "Combat acharné",
        name_jp: "ファイト・オア・フライト",
        name_kr: "임전무퇴",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "PLD",
        type: "Buff",
        icon: "https://xivapi.com/i/010000/010155.png",
        color: "--filter-light-purple",
        order: 0,
    },
    {
        id: 1368,
        name: "Requiescat",
        name_cn: "安魂祈祷",
        name_de: "Requiescat",
        name_en: "Requiescat",
        name_fr: "Requiescat",
        name_jp: "レクイエスカット",
        name_kr: "안식 기도",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "PLD",
        type: "Buff",
        icon: "https://xivapi.com/i/012000/012514.png",
        color: "--filter-dark-blue",
        order: 1,
    },
    // Mitigation
    {
        id: 17,
        name: "Sentinel",
        name_cn: "预警",
        name_de: "Sentinel",
        name_en: "Sentinel",
        name_fr: "Sentinelle",
        name_jp: "センチネル",
        name_kr: "경계",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "PLD",
        level: 38,
        duration: 15,
        cooldown: 120,
        type: "Mitigation",
        icon: "https://xivapi.com/i/000000/000151.png",
        color: "--filter-light-blue",
        order: 0,
    },
    {
        id: 3542,
        name: "Sheltron",
        name_cn: "盾阵",
        name_de: "Schiltron",
        name_en: "Sheltron",
        name_fr: "Schiltron",
        name_jp: "シェルトロン",
        name_kr: "방벽",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "PLD",
        level: 35,
        duration: 6,
        cooldown: 5,
        type: "Mitigation",
        icon: "https://xivapi.com/i/002000/002510.png",
        color: "--filter-light-blue",
        order: 1,
    },
    {
        id: 7382,
        name: "Intervention",
        name_cn: "干预",
        name_de: "Intervention",
        name_en: "Intervention",
        name_fr: "Intervention",
        name_jp: "インターベンション",
        name_kr: "중재",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "PLD",
        level: 62,
        duration: 6,
        cooldown: 10,
        type: "Mitigation",
        icon: "https://xivapi.com/i/002000/002512.png",
        color: "--filter-light-blue",
        order: 2,
    },
    {
        id: 27,
        name: "Cover",
        name_cn: "保护",
        name_de: "Deckung",
        name_en: "Cover",
        name_fr: "Couverture",
        name_jp: "かばう",
        name_kr: "감싸기",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "PLD",
        level: 45,
        duration: 12,
        cooldown: 120,
        type: "Mitigation",
        icon: "https://xivapi.com/i/002000/002501.png",
        color: "--filter-light-blue",
        order: 3,
    },
    {
        id: 7385,
        name: "Passage of Arms",
        name_cn: "武装戍卫",
        name_de: "Waffengang",
        name_en: "Passage of Arms",
        name_fr: "Passe d'armes",
        name_jp: "パッセージ・オブ・アームズ",
        name_kr: "결연한 수호자",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "PLD",
        level: 70,
        duration: 18,
        cooldown: 120,
        type: "Mitigation",
        icon: "https://xivapi.com/i/002000/002515.png",
        color: "--filter-light-blue",
        order: 4,
    },
    {
        id: 3540,
        name: "Divine Veil",
        name_cn: "圣光幕帘",
        name_de: "Heiliger Quell",
        name_en: "Divine Veil",
        name_fr: "Voile divin",
        name_jp: "ディヴァインヴェール",
        name_kr: "신성한 보호막",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "PLD",
        level: 56,
        duration: 30,
        cooldown: 90,
        type: "Mitigation",
        icon: "https://xivapi.com/i/002000/002508.png",
        color: "--filter-light-blue",
        order: 5,
    },
    {
        id: 30,
        name: "Hallowed Ground",
        name_cn: "神圣领域",
        name_de: "Heiliger Boden",
        name_en: "Hallowed Ground",
        name_fr: "Invincible",
        name_jp: "インビンシブル",
        name_kr: "천하무적",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "PLD",
        level: 50,
        duration: 10,
        cooldown: 420,
        type: "Mitigation",
        icon: "https://xivapi.com/i/002000/002502.png",
        color: "--filter-light-blue",
        order: 6,
    },
    // Party Cooldowns
    {
        id: 30,
        name: "Hallowed Ground",
        name_cn: "神圣领域",
        name_de: "Heiliger Boden",
        name_en: "Hallowed Ground",
        name_fr: "Invincible",
        name_jp: "インビンシブル",
        name_kr: "천하무적",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "PLD",
        level: 50,
        duration: 10,
        cooldown: 420,
        type: "Party",
        icon: "https://xivapi.com/i/002000/002502.png",
        color: "--filter-light-blue",
        order: 0,
    },
    {
        id: 7385,
        name: "Passage of Arms",
        name_cn: "武装戍卫",
        name_de: "Waffengang",
        name_en: "Passage of Arms",
        name_fr: "Passe d'armes",
        name_jp: "パッセージ・オブ・アームズ",
        name_kr: "결연한 수호자",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "PLD",
        level: 70,
        duration: 18,
        cooldown: 120,
        type: "Party",
        icon: "https://xivapi.com/i/002000/002515.png",
        color: "--filter-light-blue",
        order: 1,
    },
    // RDM
    // Raid Buffs
    {
        id: 7520,
        name: "Embolden",
        name_cn: "wa",
        name_de: "Ermutigen",
        name_en: "Embolden",
        name_fr: "Enhardissement",
        name_jp: "エンボルデン",
        name_kr: "성원",
        enabled: true,
        tts: true,
        ttstype: 2,
        job: "RDM",
        level: 58,
        duration: 20,
        cooldown: 120,
        type: "RaidBuff",
        icon: "https://xivapi.com/i/003000/003218.png",
        color: "--filter-dark-red",
        order: 0,
    },
    // SAM
    // DoTs
    {
        id: 1228,
        name: "Higanbana",
        name_cn: "彼岸花",
        name_de: "Higanbana",
        name_en: "Higanbana",
        name_fr: "Higanbana",
        name_jp: "彼岸花",
        name_kr: "피안화",
        enabled: true,
        tts: true,
        ttstype: 1,
        job: "SAM",
        type: "DoT",
        icon: "https://xivapi.com/i/013000/013304.png",
        color: "--filter-orange",
        order: 0,
    },
    // Buffs
    {
        id: 1298,
        name: "Jinpu",
        name_cn: "阵风",
        name_de: "Jinpu",
        name_en: "Jinpu",
        name_fr: "Jinpû",
        name_jp: "陣風",
        name_kr: "진풍",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "SAM",
        type: "Buff",
        icon: "https://xivapi.com/i/013000/013301.png",
        color: "--filter-light-gold",
        order: 0,
    },
    {
        id: 1299,
        name: "Shifu",
        name_cn: "士风",
        name_de: "Shifu",
        name_en: "Shifu",
        name_fr: "Shifû",
        name_jp: "士風",
        name_kr: "사풍",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "SAM",
        type: "Buff",
        icon: "https://xivapi.com/i/013000/013302.png",
        color: "--filter-grey",
        order: 1,
    },
    // SCH
    // DoTs
    {
        id: 179,
        name: "Bio",
        name_cn: "毒菌",
        name_de: "Bio",
        name_en: "Bio",
        name_fr: "Bactérie",
        name_jp: "バイオ",
        name_kr: "바이오",
        enabled: true,
        tts: true,
        ttstype: 1,
        job: "SCH",
        type: "DoT",
        icon: "https://xivapi.com/i/010000/010504.png",
        color: "--filter-dark-green",
        order: 0,
    },
    {
        id: 189,
        name: "Bio II",
        name_cn: "猛毒菌",
        name_de: "Biora",
        name_en: "Bio II",
        name_fr: "Extra Bactérie",
        name_jp: "バイオラ",
        name_kr: "바이오라",
        enabled: true,
        tts: true,
        ttstype: 1,
        job: "SCH",
        type: "DoT",
        icon: "https://xivapi.com/i/010000/010505.png",
        color: "--filter-dark-green",
        order: 0,
    },
    {
        id: 1895,
        name: "Biolysis",
        name_cn: "蛊毒法",
        name_de: "Causae et Curae",
        name_en: "Biolysis",
        name_fr: "Loi de l'infection",
        name_jp: "蠱毒法",
        name_kr: "고독법",
        enabled: true,
        tts: true,
        ttstype: 1,
        job: "SCH",
        type: "DoT",
        icon: "https://xivapi.com/i/012000/012812.png",
        color: "--filter-baby-blue",
        order: 0,
    },
    // Raid Buffs
    {
        id: 7436,
        name: "Chain Stratagem",
        name_cn: "连环计",
        name_de: "Kritische Strategie",
        name_en: "Chain Stratagem",
        name_fr: "Stratagèmes entrelacés",
        name_jp: "連環計",
        name_kr: "연환계",
        enabled: true,
        tts: true,
        ttstype: 2,
        job: "SCH",
        level: 66,
        duration: 15,
        cooldown: 120,
        type: "RaidBuff",
        icon: "https://xivapi.com/i/002000/002815.png",
        color: "--filter-dark-red",
        order: 0,
    },
    // Party Cooldowns
    {
        id: 188,
        name: "Sacred Soil",
        name_cn: "野战治疗阵",
        name_de: "Geweihte Erde",
        name_en: "Sacred Soil",
        name_fr: "Dogme de survie",
        name_jp: "野戦治療の陣",
        name_kr: "야전치유진",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "SCH",
        level: 50,
        duration: 15,
        cooldown: 30,
        type: "Party",
        icon: "https://xivapi.com/i/002000/002804.png",
        color: "--filter-light-blue",
        order: 0,
    },
    // SMN
    // DoTs
    {
        id: 179,
        name: "Bio",
        name_cn: "毒菌",
        name_de: "Bio",
        name_en: "Bio",
        name_fr: "Bactérie",
        name_jp: "バイオ",
        name_kr: "바이오",
        enabled: true,
        tts: true,
        ttstype: 1,
        job: "SMN",
        type: "DoT",
        icon: "https://xivapi.com/i/010000/010504.png",
        color: "--filter-dark-green",
        order: 0,
    },
    {
        id: 189,
        name: "Bio II",
        name_cn: "猛毒菌",
        name_de: "Biora",
        name_en: "Bio II",
        name_fr: "Extra Bactérie",
        name_jp: "バイオラ",
        name_kr: "바이오라",
        enabled: true,
        tts: true,
        ttstype: 1,
        job: "SMN",
        type: "DoT",
        icon: "https://xivapi.com/i/010000/010505.png",
        color: "--filter-dark-green",
        order: 0,
    },
    {
        id: 1214,
        name: "Bio III",
        name_cn: "剧毒菌",
        name_de: "Bioga",
        name_en: "Bio III",
        name_fr: "Méga Bactérie",
        name_jp: "バイオガ",
        name_kr: "바이오가",
        enabled: true,
        tts: true,
        ttstype: 1,
        job: "SMN",
        type: "DoT",
        icon: "https://xivapi.com/i/012000/012682.png",
        color: "--filter-dark-green",
        order: 0,
    },
    {
        id: 180,
        name: "Miasma",
        name_cn: "瘴气",
        name_de: "Miasma",
        name_en: "Miasma",
        name_fr: "Miasmes",
        name_jp: "ミアズマ",
        name_kr: "미아즈마",
        enabled: true,
        tts: true,
        ttstype: 1,
        job: "SMN",
        type: "DoT",
        icon: "https://xivapi.com/i/010000/010506.png",
        color: "--filter-baby-blue",
        order: 1,
    },
    {
        id: 188,
        name: "Miasma II",
        name_cn: "瘴疠",
        name_de: "Miasra",
        name_en: "Miasma II",
        name_fr: "Extra Miasmes",
        name_jp: "ミアズラ",
        name_kr: "미아즈라",
        enabled: true,
        tts: true,
        ttstype: 1,
        job: "SMN",
        type: "DoT",
        icon: "https://xivapi.com/i/010000/010507.png",
        color: "--filter-baby-blue",
        order: 1,
    },
    {
        id: 1215,
        name: "Miasma III",
        name_cn: "瘴暍",
        name_de: "Miasga",
        name_en: "Miasma III",
        name_fr: "Méga Miasmes",
        name_jp: "ミアズガ",
        name_kr: "미아즈가",
        enabled: true,
        tts: true,
        ttstype: 1,
        job: "SMN",
        type: "DoT",
        icon: "https://xivapi.com/i/012000/012683.png",
        color: "--filter-baby-blue",
        order: 1,
    },
    // Stacks
    {
        id: 1212,
        name: "Further Ruin",
        name_cn: "毁坏强化",
        name_de: "Verbessertes Ruinra",
        name_en: "Further Ruin",
        name_fr: "Extra Ruine renforcée",
        name_jp: "ルインラ強化",
        name_kr: "루인라 강화",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "SMN",
        type: "Stacks",
        icon: "https://xivapi.com/i/019000/019481.png",
        color: "--filter-dark-blue",
        order: 0,
    },
    {
        id: 7426,
        name: "Ruin IV",
        name_cn: "毁绝",
        name_de: "Ruinka",
        name_en: "Ruin IV",
        name_fr: "Giga Ruine",
        name_jp: "ルインジャ",
        name_kr: "루인쟈",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "SMN",
        type: "StackSpender",
        icon: "https://xivapi.com/i/002000/002686.png",
        color: "--filter-dark-blue",
        order: 0,
    },
    // Raid Buffs
    {
        id: 7423,
        name: "Aetherpact",
        name_cn: "以太契约",
        name_de: "Ätherpakt",
        name_en: "Aetherpact",
        name_fr: "Pacte d'éther",
        name_jp: "エーテルパクト",
        name_kr: "에테르 서약",
        enabled: true,
        tts: true,
        ttstype: 2,
        job: "SMN",
        level: 64,
        duration: 15,
        cooldown: 180,
        type: "RaidBuff",
        icon: "https://xivapi.com/i/002000/002688.png",
        color: "--filter-dark-red",
        order: 0,
    },
    // WAR
    // Buffs
    {
        id: 86,
        name: "Berserk",
        name_cn: "狂暴",
        name_de: "Tollwut",
        name_en: "Berserk",
        name_fr: "Berserk",
        name_jp: "バーサク",
        name_kr: "광폭화",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "WAR",
        type: "Buff",
        icon: "https://xivapi.com/i/010000/010253.png",
        color: "--filter-bright-red",
        order: 0,
    },
    {
        id: 1177,
        name: "Inner Release",
        name_cn: "原初的解放",
        name_de: "Urbefreiung",
        name_en: "Inner Release",
        name_fr: "Relâchement bestial",
        name_jp: "原初の解放",
        name_kr: "원초의 해방",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "WAR",
        type: "Buff",
        icon: "https://xivapi.com/i/012000/012556.png",
        color: "--filter-bright-red",
        order: 1,
    },
    {
        id: 90,
        name: "Storm's Eye",
        name_cn: "暴风碎",
        name_de: "Sturmbrecher",
        name_en: "Storm's Eye",
        name_fr: "Œil de la tempête",
        name_jp: "シュトルムブレハ",
        name_kr: "폭풍의 눈",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "WAR",
        type: "Buff",
        icon: "https://xivapi.com/i/010000/010263.png",
        color: "--filter-light-purple",
        order: 2,
    },
    // Mitigation
    {
        id: 3551,
        name: "Raw Intuition",
        name_cn: "原初的直觉",
        name_de: "Ur-Instinkt",
        name_en: "Raw Intuition",
        name_fr: "Intuition pure",
        name_jp: "原初の直感",
        name_kr: "원초의 직감",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "WAR",
        level: 56,
        duration: 6,
        cooldown: 25,
        type: "Mitigation",
        icon: "https://xivapi.com/i/002000/002559.png",
        color: "--filter-light-blue",
        order: 0,
        extra: {
            shares_cooldown: 16464,
        },
    },
    {
        id: 16464,
        name: "Nascent Flash",
        name_cn: "原初的勇猛",
        name_de: "Urflackern",
        name_en: "Nascent Flash",
        name_fr: "Exaltation naissante",
        name_jp: "原初の猛り",
        name_kr: "원초의 분노",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "WAR",
        level: 76,
        duration: 6,
        cooldown: 25,
        type: "Mitigation",
        icon: "https://xivapi.com/i/002000/002567.png",
        color: "--filter-light-blue",
        order: 1,
        extra: {
            shares_cooldown: 3551,
        },
    },
    {
        id: 40,
        name: "Thrill of Battle",
        name_cn: "战栗",
        name_de: "Kampfrausch",
        name_en: "Thrill of Battle",
        name_fr: "Frisson de la bataille",
        name_jp: "スリル・オブ・バトル",
        name_kr: "전투의 짜릿함",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "WAR",
        level: 30,
        duration: 10,
        cooldown: 90,
        type: "Mitigation",
        icon: "https://xivapi.com/i/000000/000263.png",
        color: "--filter-light-blue",
        order: 2,
    },
    {
        id: 44,
        name: "Vengeance",
        name_cn: "复仇",
        name_de: "Rachsucht",
        name_en: "Vengeance",
        name_fr: "Représailles",
        name_jp: "ヴェンジェンス",
        name_kr: "보복",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "WAR",
        level: 38,
        duration: 15,
        cooldown: 120,
        type: "Mitigation",
        icon: "https://xivapi.com/i/000000/000267.png",
        color: "--filter-light-blue",
        order: 3,
    },
    {
        id: 7388,
        name: "Shake It Off",
        name_cn: "摆脱",
        name_de: "Abschütteln",
        name_en: "Shake It Off",
        name_fr: "Débarrassage",
        name_jp: "シェイクオフ",
        name_kr: "뿌리치기",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "WAR",
        level: 68,
        duration: 15,
        cooldown: 90,
        type: "Mitigation",
        icon: "https://xivapi.com/i/002000/002563.png",
        color: "--filter-light-blue",
        order: 4,
    },
    {
        id: 43,
        name: "Holmgang",
        name_cn: "死斗",
        name_de: "Holmgang",
        name_en: "Holmgang",
        name_fr: "Holmgang",
        name_jp: "ホルムギャング",
        name_kr: "일대일 결투",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "WAR",
        level: 42,
        duration: 8,
        cooldown: 240,
        type: "Mitigation",
        icon: "https://xivapi.com/i/000000/000266.png",
        color: "--filter-light-blue",
        order: 5,
    },
    // Party Cooldowns
    {
        id: 43,
        name: "Holmgang",
        name_cn: "死斗",
        name_de: "Holmgang",
        name_en: "Holmgang",
        name_fr: "Holmgang",
        name_jp: "ホルムギャング",
        name_kr: "일대일 결투",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "WAR",
        level: 42,
        duration: 8,
        cooldown: 240,
        type: "Party",
        icon: "https://xivapi.com/i/000000/000266.png",
        color: "--filter-light-blue",
        order: 0,
    },
    {
        id: 7388,
        name: "Shake It Off",
        name_cn: "摆脱",
        name_de: "Abschütteln",
        name_en: "Shake It Off",
        name_fr: "Débarrassage",
        name_jp: "シェイクオフ",
        name_kr: "뿌리치기",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "WAR",
        level: 68,
        duration: 15,
        cooldown: 90,
        type: "Party",
        icon: "https://xivapi.com/i/002000/002563.png",
        color: "--filter-light-blue",
        order: 1,
    },
    // WHM
    // DoTs
    {
        id: 143,
        name: "Aero",
        name_cn: "疾风",
        name_de: "Wind",
        name_en: "Aero",
        name_fr: "Vent",
        name_jp: "エアロ",
        name_kr: "에어로",
        enabled: true,
        tts: true,
        ttstype: 1,
        job: "WHM",
        type: "DoT",
        icon: "https://xivapi.com/i/010000/010403.png",
        color: "--filter-green-blue",
        order: 0,
    },
    {
        id: 144,
        name: "Aero II",
        name_cn: "烈风",
        name_de: "Windra",
        name_en: "Aero II",
        name_fr: "Extra Vent",
        name_jp: "エアロラ",
        name_kr: "에어로라",
        enabled: true,
        tts: true,
        ttstype: 1,
        job: "WHM",
        type: "DoT",
        icon: "https://xivapi.com/i/010000/010409.png",
        color: "--filter-green-blue",
        order: 0,
    },
    {
        id: 798,
        name: "Aero III",
        name_cn: "暴风",
        name_de: "Windga",
        name_en: "Aero III",
        name_fr: "Méga Vent",
        name_jp: "エアロガ",
        name_kr: "에어로가",
        enabled: true,
        tts: true,
        ttstype: 1,
        job: "WHM",
        type: "DoT",
        icon: "https://xivapi.com/i/012000/012630.png",
        color: "--filter-green-blue",
        order: 0,
    },
    {
        id: 1871,
        name: "Dia",
        name_cn: "天辉",
        name_de: "Dia",
        name_en: "Dia",
        name_fr: "Lumen",
        name_jp: "ディア",
        name_kr: "디아",
        enabled: true,
        tts: true,
        ttstype: 1,
        job: "WHM",
        type: "DoT",
        icon: "https://xivapi.com/i/012000/012635.png",
        color: "--filter-baby-blue",
        order: 0,
    },
    // Buffs
    {
        id: 157,
        name: "Presence of Mind",
        name_cn: "神速咏唱",
        name_de: "Geistesgegenwart",
        name_en: "Presence of Mind",
        name_fr: "Présence d'esprit",
        name_jp: "神速魔",
        name_kr: "쾌속의 마법",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "WHM",
        type: "Buff",
        icon: "https://xivapi.com/i/012000/012627.png",
        color: "--filter-baby-blue",
        order: 0,
    },
    // Party Cooldowns
    {
        id: 140,
        name: "Benediction",
        name_cn: "天赐祝福",
        name_de: "Benediktion",
        name_en: "Benediction",
        name_fr: "Bénédiction",
        name_jp: "ベネディクション",
        name_kr: "거룩한 축복",
        enabled: true,
        tts: true,
        ttstype: 0,
        job: "WHM",
        level: 50,
        duration: 0,
        cooldown: 180,
        type: "Party",
        icon: "https://xivapi.com/i/002000/002627.png",
        color: "--filter-light-blue",
        order: 0,
    },
];
